// Function to create celestial objects (planets, moons, sun)
const createCelestialObject = ({
  name,
  displayName,
  caption,
  description,
  year,
  day,
  moons = 0,
  distanceFromSun = 0,
  minTemp = null,
  maxTemp = null,
  meanTemp = null,
  radius,
  timesLarger,
  orbitalVelocity,
  orbitObject,
  orbitalRadius,
  scaledOrbitalRadius,
  rotationVelocity,
  orbitalInclination,
  axialTilt,
}) => ({
  name,
  displayName,
  caption,
  description,
  year,
  day,
  moons,
  distanceFromSun,
  minTemp,
  maxTemp,
  meanTemp,
  radius,
  timesLarger,
  orbitalVelocity,
  orbitObject,
  orbitalRadius,
  scaledOrbitalRadius,
  rotationVelocity,
  orbitalInclination,
  axialTilt,
});

// Array of all celestial bodies
export const PLANETS = [
  // Sun
  createCelestialObject({
    name: "sun",
    displayName: "The Sun",
    caption: "G-Type Main-Sequence Star (G2V)",
    description:
      "The Sun powers life on Earth and dominates our solar system, with a core temperature of 15 million °C (27 million °F).",
    year: "230 million Earth years",
    day: "25.4 Earth days at equator, 35 Earth days at poles",
    radius: 695700,
    meanTemp: 5778,
    timesLarger: 109,
    orbitalVelocity: 0,
    orbitObject: null,
    orbitalRadius: 0,
    scaledOrbitalRadius: 0,
    rotationVelocity: 2,
    orbitalInclination: 7.25,
    axialTilt: 7.25,
  }),

  // Planets
  createCelestialObject({
    name: "mercury",
    displayName: "Mercury",
    caption: "The Fleet-Footed Planet",
    description:
      "Mercury, the smallest and fastest planet in the solar system, experiences extreme temperature variations and has a Sun that appears 3 times larger than it does from Earth.",
    year: "87.97 Earth days",
    day: "58.6 Earth days",
    moons: 0,
    distanceFromSun: 0.387,
    minTemp: -173,
    maxTemp: 427,
    radius: 2439.7,
    timesLarger: 0.38,
    orbitalVelocity: 47.36,
    orbitObject: "sun",
    orbitalRadius: 57909227,
    scaledOrbitalRadius: 24,
    rotationVelocity: 3.026,
    orbitalInclination: 7.01,
    axialTilt: 0.034,
  }),

  createCelestialObject({
    name: "venus",
    displayName: "Venus",
    caption: "Earth's Twin with a Scorching Atmosphere",
    description:
      "Venus, often called Earth's twin due to its similar size, is the hottest planet in the solar system. Its thick atmosphere causes a runaway greenhouse effect, trapping heat.",
    year: "224.7 Earth days",
    day: "243 Earth days",
    moons: 0,
    distanceFromSun: 0.723,
    meanTemp: 464,
    radius: 6051.8,
    timesLarger: 0.95,
    orbitalVelocity: 35.02,
    orbitObject: "sun",
    orbitalRadius: 108208930,
    scaledOrbitalRadius: 31,
    rotationVelocity: 1.81,
    orbitalInclination: 3.39,
    axialTilt: 177.36,
  }),

  createCelestialObject({
    name: "earth",
    displayName: "Earth",
    caption: "The Vibrant Blue Planet",
    description:
      "Earth is the only planet known to have liquid water on its surface, a breathable atmosphere, and a protective shield against meteoroids.",
    year: "365.256 Earth days",
    day: "24 hours",
    moons: 1,
    distanceFromSun: 1,
    minTemp: -89.2,
    maxTemp: 56.7,
    radius: 6371,
    timesLarger: 1,
    orbitalVelocity: 29.78,
    orbitObject: "sun",
    orbitalRadius: 149597870.7,
    scaledOrbitalRadius: 37,
    rotationVelocity: 0.465,
    orbitalInclination: 0,
    axialTilt: 23.44,
  }),

  createCelestialObject({
    name: "mars",
    displayName: "Mars",
    caption: "The Scarlet World",
    description:
      "Mars, known for its striking red color from iron oxide, is a top candidate for future exploration. The Perseverance rover is actively collecting samples that might return to Earth by 2033.",
    year: "1.88 Earth years",
    day: "24.6 hours",
    moons: 2,
    distanceFromSun: 1.524,
    minTemp: -125,
    maxTemp: 20,
    radius: 3389.5,
    timesLarger: 0.53,
    orbitalVelocity: 24.07,
    orbitObject: "sun",
    orbitalRadius: 227943824,
    scaledOrbitalRadius: 45,
    rotationVelocity: 0.241,
    orbitalInclination: 1.85,
    axialTilt: 25.19,
  }),

  createCelestialObject({
    name: "jupiter",
    displayName: "Jupiter",
    caption: "The Majestic Giant",
    description:
      "Jupiter, the largest planet in our solar system, is renowned for its Great Red Spot—a colossal storm that dwarfs Earth and has been raging for centuries.",
    year: "11.86 Earth years",
    day: "9.93 hours",
    moons: 79,
    distanceFromSun: 5.204,
    meanTemp: -108,
    radius: 69911,
    timesLarger: 11.2,
    orbitalVelocity: 13.07,
    orbitObject: "sun",
    orbitalRadius: 778547200,
    scaledOrbitalRadius: 72,
    rotationVelocity: 12.6,
    orbitalInclination: 1.3,
    axialTilt: 3.13,
  }),

  createCelestialObject({
    name: "saturn",
    displayName: "Saturn",
    caption: "The Majestic Ringed Giant",
    description:
      "Saturn is famous for its breathtaking rings, the most elaborate and extensive of any planet in our solar system, featuring 7 major rings that are a sight to behold.",
    year: "29.45 Earth years",
    day: "10.7 hours",
    moons: 82,
    distanceFromSun: 9.582,
    meanTemp: -138,
    radius: 58232,
    timesLarger: 9.4,
    orbitalVelocity: 9.69,
    orbitObject: "sun",
    orbitalRadius: 1433449370,
    scaledOrbitalRadius: 108,
    rotationVelocity: 9.87,
    orbitalInclination: 2.49,
    axialTilt: 26.73,
  }),

  createCelestialObject({
    name: "uranus",
    displayName: "Uranus",
    caption: "The Tilted Ice Giant",
    description:
      "Uranus stands out as a frigid gas giant with an extreme axial tilt, causing it to roll along its orbit. Its striking blue hue and sideways rotation make it one of the most unusual planets in our solar system.",
    year: "84 Earth years",
    day: "17.24 hours",
    moons: 27,
    distanceFromSun: 19.191,
    meanTemp: -197.15,
    radius: 25362,
    timesLarger: 4.0,
    orbitalVelocity: 6.81,
    orbitObject: "sun",
    orbitalRadius: 2870990000,
    scaledOrbitalRadius: 145,
    rotationVelocity: 2.59,
    orbitalInclination: 0.77,
    axialTilt: 97.77,
  }),

  createCelestialObject({
    name: "neptune",
    displayName: "Neptune",
    caption: "The Distant Blue World",
    description:
      "Neptune, the outermost planet in our solar system, is renowned for its deep blue hue and powerful storms. This icy giant was closely studied by NASA's Voyager 2 during its 1989 flyby, revealing its dynamic atmosphere and striking color.",
    year: "164.8 Earth years",
    day: "16.08 hours",
    moons: 14,
    distanceFromSun: 30.07,
    meanTemp: -214,
    radius: 24622,
    timesLarger: 3.9,
    orbitalVelocity: 5.43,
    orbitObject: "sun",
    orbitalRadius: 4498390000,
    scaledOrbitalRadius: 180,
    rotationVelocity: 2.68,
    orbitalInclination: 1.77,
    axialTilt: 28.32,
  }),

  // Moons
  createCelestialObject({
    name: "moon",
    displayName: "Earth's Moon",
    caption: "The Celestial Companion",
    description:
      "Earth's Moon is the fifth largest moon in our solar system and has been the site of human exploration since 1969. It is a key influence on Earth's tides and has been visited by 24 astronauts and numerous robotic missions.",
    year: "27.32 Earth days",
    radius: 1737.4,
    timesLarger: 0.27,
    orbitObject: "earth",
    orbitalRadius: 384400,
    scaledOrbitalRadius: 5,
    orbitalVelocity: 1.58,
    rotationVelocity: 1.58,
    orbitalInclination: 5.14,
    axialTilt: 1.54,
  }),

  createCelestialObject({
    name: "io",
    displayName: "Io",
    caption: "The Volcanic Dynamo",
    description:
      "Io, one of Jupiter's major moons, stands out for its extreme volcanic activity, featuring lava lakes and frequent eruptions. Its vibrant surface and dramatic geological features make it a fascinating subject of study.",
    year: "1.77 Earth days",
    radius: 1821.6,
    timesLarger: 0.285,
    distance: 421700,
    meanTemp: -143,
    orbitalVelocity: 17.334,
    orbitObject: "jupiter",
    orbitalRadius: 421700,
    scaledOrbitalRadius: 10,
    rotationVelocity: 1.8,
    orbitalInclination: 0.05,
  }),

  createCelestialObject({
    name: "europa",
    displayName: "Europa",
    caption: "The Ocean Moon",
    description:
      "Europa, one of Jupiter's largest moons, is renowned for its thick icy crust that conceals a vast subsurface ocean. This ocean may hold more water than all of Earth's oceans combined and could potentially harbor conditions suitable for life.",
    year: "3.55 Earth days",
    radius: 1560.8,
    timesLarger: 0.24,
    distance: 670900,
    minTemp: -260,
    maxTemp: -160,
    orbitalVelocity: 13.74,
    orbitObject: "jupiter",
    orbitalRadius: 670900,
    scaledOrbitalRadius: 13,
    rotationVelocity: 0.02,
    orbitalInclination: 0.47,
  }),

  createCelestialObject({
    name: "ganymede",
    displayName: "Ganymede",
    caption: "The Largest Moon in the Solar System",
    description:
      "Ganymede, a moon of Jupiter, surpasses Mercury in size and is the only moon with its own magnetic field. It has underground oceans and a tenuous oxygen atmosphere, making it a significant and intriguing object in our solar system.",
    year: "7.15 Earth days",
    radius: 2634.1,
    timesLarger: 0.416,
    distance: 1070400,
    minTemp: -200,
    maxTemp: -120,
    orbitalVelocity: 10.88,
    orbitObject: "jupiter",
    orbitalRadius: 1070400,
    scaledOrbitalRadius: 15,
    rotationVelocity: 0.026,
    orbitalInclination: 0.2,
  }),

  createCelestialObject({
    name: "callisto",
    displayName: "Callisto",
    caption: "The Most Heavily Cratered Moon",
    description:
      "Callisto, one of Jupiter's moons, is the most heavily cratered object in our solar system. Its surface shows minimal geological activity, but it might still have subsurface oceans hidden beneath its ancient, cratered crust.",
    year: "16.69 Earth days",
    radius: 2410.3,
    timesLarger: 0.384,
    distance: 1883000,
    minTemp: -193,
    maxTemp: -108,
    orbitalVelocity: 8.2,
    orbitObject: "jupiter",
    orbitalRadius: 1883000,
    scaledOrbitalRadius: 17.5,
    rotationVelocity: 0.01,
    orbitalInclination: 0.28,
  }),

  createCelestialObject({
    name: "titan",
    displayName: "Titan",
    caption: "Moon with Liquid Methane Lakes",
    description:
      "Titan, Saturn's largest moon, is the only moon in the solar system with a dense atmosphere and surface lakes made of liquid methane and ethane. Its thick, hazy atmosphere makes it unique among moons.",
    year: "15.9 Earth days",
    radius: 2574.7,
    timesLarger: 0.4,
    distance: 1221865,
    meanTemp: -179,
    orbitalVelocity: 5.57,
    orbitObject: "saturn",
    orbitalRadius: 1221865,
    scaledOrbitalRadius: 16,
    rotationVelocity: 0.011,
    orbitalInclination: 0.33,
  }),

  createCelestialObject({
    name: "triton",
    displayName: "Triton",
    caption: "Neptune's Coldest and Retrograde Moon",
    description:
      "Triton, Neptune's largest moon, is the coldest moon in the solar system with a mean temperature of -235°C. Its unique retrograde orbit, moving opposite to Neptune's rotation, sets it apart from other moons.",
    year: "5.88 Earth days",
    radius: 1353.4,
    timesLarger: 0.21,
    distance: 354759,
    meanTemp: -235,
    orbitalVelocity: 4.39,
    orbitObject: "neptune",
    orbitalRadius: 354759,
    scaledOrbitalRadius: 7,
    rotationVelocity: 0.017,
    orbitalInclination: 156.9,
  }),
];
